export interface LegacyArticleMeta {
  category: string;
  slug: string;
  title: string;
  date: string;
}

export const legacyCategoryLabels: Record<string, string> = {
  marketing: "Marketing",
  referencement: "Référencement",
  securite: "Sécurité",
  "hebergement-web": "Hébergement Web",
  domaine: "Domaines",
  "non-classe": "Non classé",
  wordpress: "WordPress",
  webdesign: "Web Design",
  "e-commerce": "E-commerce",
  portait: "Partenaires",
};

export const legacyArticles: LegacyArticleMeta[] = [
  { category: "marketing", slug: "adresses-emails-professionnelles-en-entreprise", title: "Adresses emails professionnelles en entreprise : pourquoi c'est essentiel", date: "27 Jan 2021" },
  { category: "marketing", slug: "pourquoi-avoir-un-site-web-pour-votre-entreprise", title: "Pourquoi avoir un site web pour votre entreprise", date: "29 Jan 2021" },
  { category: "referencement", slug: "pourquoi-est-ce-si-important-de-renouveler-un-domaine-avant-sa-date-dexpiration", title: "Pourquoi est-ce si important de renouveler un domaine avant sa date d'expiration", date: "04 Fév 2021" },
  { category: "marketing", slug: "7-raisons-entreprise-besoin-un-blog", title: "7 raisons pour lesquelles votre entreprise a besoin d'un blog", date: "06 Fév 2021" },
  { category: "securite", slug: "10-taches-maintenance-wordpress", title: "10 tâches de maintenance WordPress à ne pas négliger", date: "08 Fév 2021" },
  { category: "referencement", slug: "comprendre-le-referencement-et-comment-il-fonctionne", title: "Comprendre le référencement et comment il fonctionne", date: "14 Fév 2021" },
  { category: "hebergement-web", slug: "les-principales-methodes-de-paiement-mobile-money-au-gabon", title: "Les principales méthodes de paiement mobile money au Gabon", date: "21 Fév 2023" },
  { category: "domaine", slug: "obtenir-nom-de-domaine-gratuit-spiderhoster", title: "Comment obtenir un nom de domaine gratuit avec SPIDERHOSTER", date: "21 Fév 2023" },
  { category: "marketing", slug: "necessite-service-hebergement-web-proposant-le-mobile-moyen-paiement-factures", title: "La nécessité d'un hébergement web proposant le mobile money pour vos factures", date: "21 Fév 2023" },
  { category: "marketing", slug: "strategie-de-vente-magasin-en-ligne", title: "Stratégie de vente pour votre magasin en ligne", date: "21 Fév 2023" },
  { category: "non-classe", slug: "divi-et-elementor-quel-est-le-meilleur-constructeur-de-pages-web", title: "Divi et Elementor : quel est le meilleur constructeur de pages web ?", date: "05 Mar 2023" },
  { category: "wordpress", slug: "7-choses-que-vous-ignorez-peut-etre-au-sujet-de-cms-wordpress", title: "7 choses que vous ignorez peut-être au sujet du CMS WordPress", date: "05 Mar 2023" },
  { category: "referencement", slug: "comment-obtenir-un-score-de-100-sur-google-pagespeed-insights", title: "Comment obtenir un score de 100 sur Google PageSpeed Insights", date: "05 Mar 2023" },
  { category: "marketing", slug: "des-adresses-emails-pro-pour-les-entreprises-gabonaises-pourquoi-chez-spiderhoster-com", title: "Des adresses emails pro pour les entreprises gabonaises : pourquoi chez SPIDERHOSTER.com", date: "07 Mar 2023" },
  { category: "wordpress", slug: "comment-creer-un-site-web-wordpress-en-5-etapes-faciles", title: "Comment créer un site web WordPress en 5 étapes faciles", date: "16 Mar 2023" },
  { category: "webdesign", slug: "wordpress-org-et-wordpress-com", title: "WordPress.org et WordPress.com : quelles différences ?", date: "16 Mar 2023" },
  { category: "wordpress", slug: "cest-quoi-wordpress", title: "C'est quoi WordPress ?", date: "18 Mar 2023" },
  { category: "wordpress", slug: "dois-je-utiliser-un-hebergement-wordpress-ou-un-hebergement-mutualise", title: "Dois-je utiliser un hébergement WordPress ou un hébergement mutualisé ?", date: "18 Juil 2023" },
  { category: "hebergement-web", slug: "hebergement-web-en-afrique-centrale-avec-paiement-gimacpay", title: "Hébergement web en Afrique Centrale avec paiement GIMACPAY", date: "19 Juil 2023" },
  { category: "hebergement-web", slug: "hebergez-vos-sites-web-a-port-gentil-gabon-avec-spiderhoster-com", title: "Hébergez vos sites web à Port-Gentil, Gabon avec SPIDERHOSTER.com", date: "19 Juil 2023" },
  { category: "marketing", slug: "comment-creer-une-entreprise-en-ligne-prospere-au-gabon", title: "Comment créer une entreprise en ligne prospère au Gabon", date: "20 Juil 2023" },
  { category: "wordpress", slug: "comment-mettre-en-ligne-un-site-web-wordpress-rapidement", title: "Comment mettre en ligne un site web WordPress rapidement", date: "15 Août 2023" },
  { category: "non-classe", slug: "les-jeunes-entrepreneurs-au-gabon-pieges-par-le-systeme", title: "Les jeunes entrepreneurs au Gabon piégés par le système", date: "06 Nov 2023" },
  { category: "domaine", slug: "5-tactiques-sournoises-utilisees-par-les-registraires-de-domaine-bon-marche", title: "5 tactiques sournoises utilisées par les registraires de domaine bon marché", date: "10 Jan 2024" },
  { category: "webdesign", slug: "comment-creer-votre-propre-site-web", title: "Comment créer votre propre site web", date: "10 Jan 2024" },
  { category: "marketing", slug: "gagner-argent-avec-son-blog", title: "Comment gagner de l'argent avec son blog", date: "10 Jan 2024" },
  { category: "securite", slug: "pourquoi-securiser-votre-site-web-avec-certificat-ssl", title: "Pourquoi sécuriser votre site web avec un certificat SSL", date: "10 Jan 2024" },
  { category: "hebergement-web", slug: "quest-ce-que-cloudlinux", title: "Qu'est-ce que CloudLinux ?", date: "10 Jan 2024" },
  { category: "referencement", slug: "un-domaine-ou-sous-domaine", title: "Un domaine ou un sous-domaine : lequel choisir ?", date: "10 Jan 2024" },
  { category: "referencement", slug: "optimiser-les-images-pour-ameliorer-la-vitesse-dun-site-wordpress", title: "Optimiser les images pour améliorer la vitesse d'un site WordPress", date: "10 Jan 2024" },
  { category: "hebergement-web", slug: "hebergement-cpanel-et-softaculous", title: "Hébergement cPanel et Softaculous : tout savoir", date: "10 Jan 2024" },
  { category: "webdesign", slug: "demarrer-votre-premier-site-web", title: "Démarrer votre premier site web", date: "10 Jan 2024" },
  { category: "domaine", slug: "quest-ce-quun-domaine-de-premier-niveau-tld", title: "Qu'est-ce qu'un domaine de premier niveau (TLD) ?", date: "10 Jan 2024" },
  { category: "webdesign", slug: "comment-proceder-mise-en-scene-votre-site-web-cpanel", title: "Comment procéder à la mise en scène de votre site web sous cPanel", date: "10 Jan 2024" },
  { category: "referencement", slug: "liens-internes-et-liens-externes-pour-le-referencement", title: "Liens internes et liens externes pour le référencement", date: "10 Jan 2024" },
  { category: "hebergement-web", slug: "un-hebergement-wordpress-optimise", title: "Un hébergement WordPress optimisé : les avantages", date: "13 Jan 2024" },
  { category: "marketing", slug: "exploration-des-opportunites-daffaires-au-gabon", title: "Exploration des opportunités d'affaires au Gabon", date: "16 Jan 2024" },
  { category: "e-commerce", slug: "comment-bien-demarrer-une-boutique-en-ligne-reussie-conseils-pour-les-debutants", title: "Comment bien démarrer une boutique en ligne réussie : conseils pour les débutants", date: "14 Jan 2024" },
  { category: "wordpress", slug: "6-erreurs-wordpress-les-plus-courantes-et-comment-les-corriger", title: "6 erreurs WordPress les plus courantes et comment les corriger", date: "14 Jan 2024" },
  { category: "securite", slug: "plugins-wordpress-securite-site-web", title: "Plugins WordPress pour sécuriser votre site web", date: "14 Jan 2024" },
  { category: "securite", slug: "comment-supprimer-les-logiciels-malveillants-de-wordpress", title: "Comment supprimer les logiciels malveillants de WordPress", date: "14 Jan 2024" },
  { category: "securite", slug: "hebergement-web-avec-certificat-ssl-gratuit", title: "Hébergement web avec certificat SSL gratuit", date: "14 Jan 2024" },
  { category: "marketing", slug: "les-10-meilleures-idees-de-business-en-ligne-a-lancer", title: "Les 10 meilleures idées de business en ligne à lancer", date: "19 Jan 2024" },
  { category: "hebergement-web", slug: "obtenez-un-hebergement-web-sur-et-fiable-a-port-gentil-au-gabon", title: "Obtenez un hébergement web sûr et fiable à Port-Gentil au Gabon", date: "27 Juil 2024" },
  { category: "hebergement-web", slug: "les-differents-modes-de-paiement-acceptes-sur-la-plateforme-dhebergement-web-spiderhoster", title: "Les différents modes de paiement acceptés sur la plateforme d'hébergement web SPIDERHOSTER", date: "27 Juil 2024" },
  { category: "domaine", slug: "acheter-un-nom-de-domaine-ga-au-gabon", title: "Acheter un nom de domaine .ga au Gabon", date: "27 Juil 2024" },
];